### ISSUE TITLE
meta2 : Problem during base deletion

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#173]
In a replicate mode, when you delete a meta2 base, sometimes a sqlite file persists on one of the involved node.

**Comment by jkasarherou** [comment]
Can you provide steps to reproduce please ?

**Comment by GuillaumeDelaporte** [comment]
This problem appears only when you have a heavy load on sds (millions of create/del container request).

I will reproduce the problem on my platform and give you all logs.

**Comment by jkasarherou** [comment]
Is the remaining sqlite db file empty?

**Comment by sebastienlapierre** [comment]
#### Reproductible issue on a OpenIOSDS ptf with repli x3 mode
**Scenario:** create 25 empty containers by 'openio' python cli, then delete them, repeat this scenario 3 times.

* Check namespace and account are empty.

* Create 25 empty containers

* Check the meta2 bdd by container are presents
75 db exist (25 x 3) => the result is fine

* Delete the containers
The first time, all the containers are often deleted.

But after have repeated this scenario 3times and despite the fact that no container are listed in the account, several meta2 bdd still remain (more than 60%)

The remaining containers bdd contain this type of admin table:
`schema_version|1.8`
`version:main.admin|1:0`
`version:main.contents|1:0`
`version:main.chunks|1:0`
`version:main.aliases|1:0`
`version:main.properties|1:0`
`sys.name|8976DEC24A4042763E50E4C5238A43BF7F3403318FBE68046F263ED349ECFFAB.1`
`sys.type|meta2`

If I repeat this scenario N times, in the end, no container can be created due to the remaining bdd stored throughout all the meta2 .

**Comment by jfsmig** [comment]
Similarly to #80, fixed at commit e61c18ffeba95fbcf4549184c74c97bcaf78c13c.
