### ISSUE TITLE
meta2 test backend: assertion failed

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#229]
```
oio.m2v2:ERROR:/home/noone/public_git/github.com/jkasarherou/oio-sds/meta2v2/test_meta2_backend.c:263:_repo_wraper: assertion failed (err == NULL): XATTR set error: Operation not supported (oio.utils, 95)
```

**Comment by jfsmig** [comment]
In #250 ...
* at commit c7885121f57e5fd055e6250e41c5537594100cb1, the lock has been moved from the repository to the service, so that tests on the repository don't require the XATTR lock to be set
* at commit cd401ff870fa6785abce5e78a0e033efafc9d951, the basedir for meta2 tests has been moved from `/tmp` to the `~/.oio/sds/data` of the user playing the tests. This directory is already used for `oio-reset.sh`, with xattr enabled for the services.
