### ISSUE TITLE
if-none-match like support

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#555]
We need some kind of if-none-match like feature:
for a content_prepare if we provide a specific flag, check if the content is not already present.
the same but with a checksum check.

**Comment by jfsmig** [comment]
Several ideas here...

Inserting a content with a path that already exists simply creates a new version of the file (excepted when the versioning is off). The direction was more toward a removal of the feature versioning=off (a reminder from the old days of openio's ancestor).

A check already exists on the content's ID that must be unique. The ID can be specified at the PUT. Checking during the PUT could be possible but would require more effort (because of the number of new arguments to pass along the chain of services).

To remain efficient, a check on the hash only won't be supported due to the lack of an index (in the container's SQLite structure) and a specific index won't be added to limit the I/O at container opening.
But an index already exists on the content's hash column, on hash *and* size.

More generally, the `content_prepare` operation is currently read-only. Such a flag would drastically increase the directory time spent.

**Comment by jfsmig** [comment]
Such a feature is too complicated, if it must be reliable over a distributed system with no lock.
In addition the purpose is not obvious.
Finally, the lack of demand (and even of any poke on the topic) lead us to deny it.
